<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

// This file handles pages, but only exists for the sake of child theme forward compatibility.

// Force full width content layout.
add_filter( 'genesis_site_layout', '__genesis_return_full_width_content' );

// Remove breadcrumbs.
remove_action( 'genesis_before_loop', 'genesis_do_breadcrumbs' );

// Remove footer widgets.
remove_action( 'genesis_before_footer', 'genesis_footer_widget_areas' );


add_action('genesis_entry_content', 'mk_meerkat_entry_content');

function mk_meerkat_entry_content() {
    $args = [
        'post_type'      => 'meerkat_projects',
        'posts_per_page' => 10,
    ];
    $loop = new WP_Query($args);
    ?>
    <div class="container row">
        <?php 
        while ($loop->have_posts()) {
            $loop->the_post();
            ?>
            <div class="project-entry-content col-12 col-md-3">
                <h3 class="project-entry-title"><?php the_title(); ?></h3>
                <?php the_post_thumbnail( 'featured-image' ); ?>
                <?php the_content(); ?>
            </div>
             <?php 
        }?>
    </div>
<?php 
}

genesis();